stages:
  - build
  - test
  - docs

# Cache dependencies to speed up subsequent runs
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - target
    - .cargo

# Build the Rust project
build:
  stage: build
  image: rust:latest
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release

# Run tests for the Rust project
test:
  stage: test
  image: rust:latest
  script:
    - cargo test

# Generate documentation
docs:
  stage: docs
  image: rust:latest
  script:
    - cargo doc --no-deps
    - mkdir -p public
    - cp -r target/doc/* public/
  artifacts:
    paths:
      - target/doc
  only:
    - main # Only generate docs for the master branch (optional, you can change this)
